# Generated by Django 5.1.15 on 2026-07-16 01:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salesforce_id", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("dropbox_root", models.CharField(blank=True, max_length=1024)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="InspectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("walk_date", models.DateField()),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ingesting", "Ingesting"),
                            ("ingested", "Ingested"),
                            ("evaluating", "Evaluating"),
                            ("ready_for_review", "Ready for review"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("dropbox_folder_path", models.CharField(max_length=1024)),
                ("contractor_notes", models.TextField(blank=True)),
                ("salesforce_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "proposed_billing_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("review_url", models.URLField(blank=True)),
                ("error_detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "previous_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="following_runs",
                        to="turns.inspectionrun",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="turns.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-walk_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("run_after", models.DateTimeField(default=django.utils.timezone.now)),
                ("dedup_key", models.CharField(blank=True, default="", max_length=200)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=128)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["run_after", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "run_after"],
                        name="turns_job_status_beb1d3_idx",
                    ),
                    models.Index(
                        fields=["job_type", "status"],
                        name="turns_job_job_typ_922618_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["queued", "running"]),
                            models.Q(("dedup_key", ""), _negated=True),
                        ),
                        fields=("dedup_key",),
                        name="uniq_active_job_dedup_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("current", "Current walk"), ("prior", "Prior walk")],
                        max_length=8,
                    ),
                ),
                ("dropbox_path", models.CharField(max_length=1024)),
                ("filename", models.CharField(max_length=512)),
                ("storage_path", models.CharField(blank=True, max_length=1024)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("bytes_original", models.BigIntegerField(blank=True, null=True)),
                ("bytes_downsampled", models.BigIntegerField(blank=True, null=True)),
                ("exif_taken_at", models.DateTimeField(blank=True, null=True)),
                ("room_label", models.CharField(blank=True, max_length=128)),
                ("subject_label", models.CharField(blank=True, max_length=128)),
                ("classification", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="turns.inspectionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_label", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("damage", "Damage"),
                            ("wear", "Wear & tear"),
                            ("missing_item", "Missing item"),
                            ("pre_existing", "Pre-existing"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=8,
                    ),
                ),
                ("billable_to_guest", models.BooleanField(default=False)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("edited", "Edited"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="turns.inspectionrun",
                    ),
                ),
                (
                    "evidence_photos",
                    models.ManyToManyField(
                        blank=True, related_name="findings", to="turns.photo"
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence"],
            },
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["run", "source"], name="turns_photo_run_id_f6537d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["run", "room_label"], name="turns_photo_run_id_af2690_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                fields=("run", "dropbox_path"), name="uniq_photo_per_run_path"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["run", "review_status"], name="turns_findi_run_id_ef493a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["run", "-confidence"], name="turns_findi_run_id_be2655_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrun",
            index=models.Index(
                fields=["property", "walk_date"], name="turns_inspe_propert_57a91b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrun",
            index=models.Index(fields=["status"], name="turns_inspe_status_93cc29_idx"),
        ),
    ]
