# Generated by Django 5.1.15 on 2026-07-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionrun",
            name="photo_folder_url",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="inspectionrun",
            name="prior_work_item_id",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="inspectionrun",
            name="salesforce_work_item_id",
            field=models.CharField(blank=True, db_index=True, max_length=18),
        ),
        migrations.AlterField(
            model_name="inspectionrun",
            name="dropbox_folder_path",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
