# Generated by Django 5.1.15 on 2026-07-16 12:34

import turns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turns", "0003_inspectionrun_evaluation_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionrun",
            name="review_token",
            field=models.CharField(
                default=turns.models._make_review_token,
                editable=False,
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="inspectionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ingesting", "Ingesting"),
                    ("ingested", "Ingested"),
                    ("evaluating", "Evaluating"),
                    ("ready_for_review", "Ready for review"),
                    ("reviewed", "Reviewed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
